from __future__ import annotations

import time
from typing import Any

from api_client import GitHubApiClient
from reporter import ValidatorOutcome


async def validate(context: dict[str, Any], sre_client) -> ValidatorOutcome:
    started = time.perf_counter()
    token = str(context.get("github_token") or "")
    repository = str(context.get("repository") or "")
    github_api_base_url = str(context.get("github_api_base_url") or "https://api.github.com")
    if not token:
        return ValidatorOutcome(
            name="pull_request",
            passed=False,
            duration_seconds=time.perf_counter() - started,
            error="GITHUB_TOKEN missing in testing-agent config",
        )

    run_id = str(context.get("run_id") or "")
    if not run_id:
        return ValidatorOutcome(
            name="pull_request",
            passed=False,
            duration_seconds=time.perf_counter() - started,
            error="Missing run_id for PR validation",
        )

    owner = (
        repository.split("/")[0] if "/" in repository else str(context.get("github_owner") or "")
    )
    branch = f"sre-fix/{run_id[:12].replace('-', '')}"

    client = GitHubApiClient(base_url=github_api_base_url, token=token)
    try:
        pulls = await client.list_pulls_by_head(repository, owner, branch, state="all")
        if not pulls:
            return ValidatorOutcome(
                name="pull_request",
                passed=False,
                duration_seconds=time.perf_counter() - started,
                error=f"No PR found for head branch {branch}",
            )

        pr = pulls[0]
        number = int(pr.get("number"))
        details = await client.get_pull(repository, number)
        body = str(details.get("body") or "")

        has_root_cause = "Root Cause Analysis" in body
        has_confidence = "Confidence" in body
        has_changes = "### Changes" in body
        has_provenance_marker = "Generated by [SRE Agent]" in body

        analysis = await sre_client.get_analysis(str(context["failure_id"]))
        scans_present = isinstance(analysis.get("validation", {}).get("scans"), dict)
        evidence_present = len(analysis.get("evidence", [])) > 0

        passed = all(
            [
                has_root_cause,
                has_confidence,
                has_changes,
                has_provenance_marker,
                scans_present,
                evidence_present,
            ]
        )
        return ValidatorOutcome(
            name="pull_request",
            passed=passed,
            duration_seconds=time.perf_counter() - started,
            details={
                "pr_number": number,
                "pr_url": details.get("html_url"),
                "has_root_cause": has_root_cause,
                "has_confidence": has_confidence,
                "has_changes": has_changes,
                "has_provenance_marker": has_provenance_marker,
                "scans_present": scans_present,
                "evidence_present": evidence_present,
            },
            error=None if passed else "PR body/artifact checks failed",
        )
    except Exception as exc:
        return ValidatorOutcome(
            name="pull_request",
            passed=False,
            duration_seconds=time.perf_counter() - started,
            error=str(exc),
        )
    finally:
        await client.close()
